name: 'Deploy Angular TIDESCL'
description: 'Deploy Angular TIDESCL App'
inputs:
  rama:  # id of input
    description: 'Branch Execution'
    required: true
    default: 'develop'
outputs:
  random-number: 
    description: "Random number"
    value: "salida"
runs:
  using: docker
  image: roylines/lambda-build-node12.x
  
- name: Install Dependencies
  run: npm install --save-dev

- name: Serverless Deploy        
  run: | 
    ./node_modules/@angular/cli/bin/ng build --c=dev --aot --extract-css --build-optimizer --optimization
    ls dist