name: 'Deploy Angular TIDESCL'
description: 'Deploy Angular TIDESCL App'
inputs:
  branch:  # id of input
    description: 'Branch Execution'
    required: true
    default: 'develop'
##outputs:
#  random-number: 
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: docker
  image: roylines/lambda-build-node12.x
  steps: 
    - run: echo Branch ${{ inputs.branch }}.
      shell: bash    

    - name: Install Dependencies
      run: npm install --save-dev

    - name: Serverless Deploy        
      run: | 
        ./node_modules/@angular/cli/bin/ng build --c=dev --aot --extract-css --build-optimizer --optimization
        ls dist
        
      


    

    #- run: echo Hello ${{ inputs.who-to-greet }}.
    #  shell: bash
    #- id: random-number-generator
    #  run: echo "::set-output name=random-id::$(echo $RANDOM)"
    #  shell: bash
    #- run: ${{ github.action_path }}/goodbye.sh
    #  shell: bash
